name: note_card
description: "Aplicativo de notas."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  # Mobx
  flutter_mobx: ^2.2.0+1
  mobx: ^2.2.3

  # Shared Preferences
  shared_preferences: ^2.2.2

  # Default
  flutter:
    sdk: flutter

dev_dependencies:
  # MobX
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.7

  # Default
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
