name: note_card
description: "Aplicativo de notas."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.0+1
  http: ^1.1.2
  mobx: ^2.2.3
  mockito: ^5.4.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
